language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - mysql -e 'create database makedrive;'
env:
  - DB_TYPE="mysql" DB_NAME="makedrive" DB_USERNAME="travis" DB_PASSWORD=""
